// TRANSLATE ACTIONS
export const TRANSLATE = 'TRANSLATE'
export const GET_DICT_LIST = 'GET_DICT_LIST'

// DICTIONARY ACTIONS
export const GET_DICTIONARIES = 'GET_DICTIONARIES'
export const GET_DICTIONARY = 'GET_DICTIONARY'
