// TRANSLATE ACTIONS
export const TRANSLATE = 'TRANSLATE'
export const GET_DICT_LIST = 'GET_DICT_LIST'

// DICTIONARY ACTIONS
export const GET_DICTIONARIES = 'GET_DICTIONARIES'
export const GET_DICTIONARY = 'GET_DICTIONARY'

// APP ACTIONS
export const SET_LOADING = 'SET_LOADING'
export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION'
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION'
