export const SORT_OPTIONS = {
    ALPHABETICAL_ASC: 'ALPHABETICAL_ASC',
    ALPHABETICAL_DESC: 'ALPHABETICAL_DESC',
    MATCH_ASC: 'MATCH_ASC',
    MATCH_DESC: 'MATCH_DESC',
}

export const WORD_COLOR = {
    '0': '#33CC33',
    '1': '#FF6600',
    '2': '#CC0000'
}
